// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Accordion = import('./accordion').XP_Accordion;
export type XP_ArticleCardList = import('./article-card-list').XP_ArticleCardList;
export type XP_Button = import('./button').XP_Button;
export type XP_CookieConsentOpen = import('./cookie-consent-open').XP_CookieConsentOpen;
export type XP_CookieConsentToggle = import('./cookie-consent-toggle').XP_CookieConsentToggle;
export type XP_Downloads = import('./downloads').XP_Downloads;
export type XP_ExpansionCard = import('./expansion-card').XP_ExpansionCard;
export type XP_Heading = import('./heading').XP_Heading;
export type XP_Image = import('./image').XP_Image;
export type XP_LinkCard = import('./link-card').XP_LinkCard;
export type XP_LinkCardList = import('./link-card-list').XP_LinkCardList;
export type XP_NewsletterSignup = import('./newsletter-signup').XP_NewsletterSignup;
export type XP_Quote = import('./quote').XP_Quote;
export type XP_SearchView = import('./search-view').XP_SearchView;
export type XP_ShowMore = import('./show-more').XP_ShowMore;
export type XP_Skyra = import('./skyra').XP_Skyra;
export type XP_TableOfContents = import('./table-of-contents').XP_TableOfContents;
export type XP_TextEditor = import('./text-editor').XP_TextEditor;
export type XP_ThemeCardList = import('./theme-card-list').XP_ThemeCardList;
export type XP_TitleIngress = import('./title-ingress').XP_TitleIngress;
export type XP_Video = import('./video').XP_Video;

declare global {
  interface XpPartMap {
    'idebanken:accordion': XP_Accordion;
    'idebanken:article-card-list': XP_ArticleCardList;
    'idebanken:button': XP_Button;
    'idebanken:cookie-consent-open': XP_CookieConsentOpen;
    'idebanken:cookie-consent-toggle': XP_CookieConsentToggle;
    'idebanken:downloads': XP_Downloads;
    'idebanken:expansion-card': XP_ExpansionCard;
    'idebanken:heading': XP_Heading;
    'idebanken:image': XP_Image;
    'idebanken:link-card': XP_LinkCard;
    'idebanken:link-card-list': XP_LinkCardList;
    'idebanken:newsletter-signup': XP_NewsletterSignup;
    'idebanken:quote': XP_Quote;
    'idebanken:search-view': XP_SearchView;
    'idebanken:show-more': XP_ShowMore;
    'idebanken:skyra': XP_Skyra;
    'idebanken:table-of-contents': XP_TableOfContents;
    'idebanken:text-editor': XP_TextEditor;
    'idebanken:theme-card-list': XP_ThemeCardList;
    'idebanken:title-ingress': XP_TitleIngress;
    'idebanken:video': XP_Video;
  }
}
