// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Accordion = import('./accordion').XP_Accordion;
export type XP_Button = import('./button').XP_Button;
export type XP_Downloads = import('./downloads').XP_Downloads;
export type XP_ExpansionCard = import('./expansion-card').XP_ExpansionCard;
export type XP_Heading = import('./heading').XP_Heading;
export type XP_Image = import('./image').XP_Image;
export type XP_InfoBox = import('./info-box').XP_InfoBox;
export type XP_LinkCard = import('./link-card').XP_LinkCard;
export type XP_LinkCardList = import('./link-card-list').XP_LinkCardList;
export type XP_SearchView = import('./search-view').XP_SearchView;
export type XP_TableOfContents = import('./table-of-contents').XP_TableOfContents;
export type XP_TextEditor = import('./text-editor').XP_TextEditor;
export type XP_TipPanel = import('./tip-panel').XP_TipPanel;
export type XP_TitleIngress = import('./title-ingress').XP_TitleIngress;

declare global {
  interface XpPartMap {
    'idebanken:accordion': XP_Accordion;
    'idebanken:button': XP_Button;
    'idebanken:downloads': XP_Downloads;
    'idebanken:expansion-card': XP_ExpansionCard;
    'idebanken:heading': XP_Heading;
    'idebanken:image': XP_Image;
    'idebanken:info-box': XP_InfoBox;
    'idebanken:link-card': XP_LinkCard;
    'idebanken:link-card-list': XP_LinkCardList;
    'idebanken:search-view': XP_SearchView;
    'idebanken:table-of-contents': XP_TableOfContents;
    'idebanken:text-editor': XP_TextEditor;
    'idebanken:tip-panel': XP_TipPanel;
    'idebanken:title-ingress': XP_TitleIngress;
  }
}
