// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Meta = import('./meta').XP_Meta;
export type XP_Tags = import('./tags').XP_Tags;

declare global {
  interface XpXData {
    'idebanken'?: {
      meta?: Meta;
      tags?: Tags;
    };
  }
}
