// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Category = import('./category').XP_Category;

declare global {
  interface XpXData {
    'idebanken'?: {
      category?: Category;
    };
  }
}
