// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Category = import('./category').XP_Category;
export type XP_Meta = import('./meta').XP_Meta;
export type XP_ThirdParty = import('./third-party').XP_ThirdParty;

declare global {
  interface XpXData {
    'idebanken'?: {
      category?: Category;
      meta?: Meta;
      'third-party'?: ThirdParty;
    };
  }
}
