// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_TextEditor = {
  /**
   * Innhold
   */
  simpleTextEditor?: string;

  /**
   * Farge på boks
   */
  boxColor?: 'neutral' | 'ib-brand-gray' | 'ib-brand-pink';

  /**
   * Vis på 1/2 sjermbredde
   */
  halfWidth: boolean;
};
