// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type TextEditor = {
  /**
   * Innhold
   */
  simpleTextEditor?: string;

  /**
   * Farge på boks
   */
  boxColor?: 'bg-white' | 'bg-brand-white' | 'bg-extra-light-pink';

  /**
   * Vis på 1/2 sjermbredde
   */
  halfWidth: boolean;
};
