// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_AktueltTags = {
  /**
   * Tema
   */
  themeTags?: Array<string> | string;

  /**
   * Type
   */
  typeTags: string;
};
