// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type CrashCourse = {
  /**
   * Backlink for lynkurset (veileder)
   */
  backlinkContent: string;

  /**
   * Etikett for backlink
   */
  backlinkLabel: string;
};
