// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_CrashCourseFunctionalButton = {
  /**
   * Vis start knapp
   */
  showStartButton: boolean;

  /**
   * Vis fullskjerm knapp
   */
  showFullscreenButton: boolean;

  /**
   * Vis tema knapp
   */
  showThemeButton: boolean;
};
