// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Kjerneartikkel = {
  /**
   * Tittel
   */
  title: string;

  /**
   * Ingress
   */
  ingress: string;

  /**
   * Kort tittel (listevisning)
   */
  shortTitle?: string;

  /**
   * Kort beskrivelse (listevisning)
   */
  description?: string;

  /**
   * Overskriv lenkekort bilde
   */
  overrideImage?: string;

  /**
   * Forfatter(e) / Kilder
   */
  authors?: Array<string> | string;

  /**
   * Publiseringsdato
   */
  publicationDate: string;
};
