// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Box = {
  /**
   * Ikon
   */
  iconName?: 'hand-shake-heart' | 'reception' | 'chat-2' | 'hand-shake' | 'person-group' | 'task-list' | 'clock';

  /**
   * Tittel
   */
  title: string;

  /**
   * Farge
   */
  brand: 'blue' | 'pink';

  /**
   * Innhold
   */
  body: string;

  /**
   * Lenker
   */
  links?: Array<string> | string;
};
