// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Video = {
  /**
   * Velg video-innhold
   */
  targetContent: string;

  /**
   * Visning før avspilling
   */
  displayType: 'small' | 'large';

  /**
   * Overstyr språk for undertekster
   */
  language?: string;
};
