// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Panel2Column = {
  /**
   * Background (Outer Box / Inner Box)
   */
  background: Array<{
    /**
     * Bakgrunnsfarge
     */
    bgColor: "bg-white" | "bg-extra-light-pink" | "bg-light-pink" | "bg-pink" | "bg-dark-blue";
  }>;

  /**
   * Venstre Kolonne - Bredde
   */
  leftSpan: "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "11";
};
