// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Guide = {
  /**
   * Tittel
   */
  title: string;

  /**
   * Ingress
   */
  ingress: string;

  /**
   * Kort beskrivelse (brukes i listevisning)
   */
  description?: string;

  /**
   * Bilde
   */
  image?: string;

  /**
   * Ikon
   */
  iconName?: 'hand-shake-heart' | 'reception' | 'chat-2' | 'hand-shake' | 'person-group' | 'task-list' | 'clock';

  /**
   * Ikonens bakgrunnsfarge
   */
  iconColor?: 'bg-white' | 'bg-pink' | 'bg-blue' | 'bg-orange' | 'bg-yellow' | 'bg-red';
};
