// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Guide = {
  /**
   * Tittel
   */
  title: string;

  /**
   * Ingress
   */
  ingress: string;

  /**
   * Kort beskrivelse (brukes i listevisning)
   */
  description?: string;
};
