// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type LinkCardList = {
  /**
   * Liste-type
   */
  list:
    | {
        /**
         * Selected
         */
        _selected: 'automatic';

        /**
         * Automatisk liste
         */
        automatic: {
          /**
           * Innholdstyper som skal hentes
           */
          contentTypes?: Array<string> | string;

          /**
           * Hent kun barn av dette innholdet
           */
          parentContent?: string;

          /**
           * Vis tittel til innholdet som er valgt over
           */
          showHeading: boolean;

          /**
           * Maks antall innhold
           */
          limit?: number;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: 'manual';

        /**
         * Manuell liste
         */
        manual: {
          /**
           * Innhold i listen
           */
          contents: Array<string> | string;
        };
      };

  /**
   * Visning
   */
  displayType: 'withIcon' | 'withImage';

  /**
   * Brand farger
   */
  brand: 'neutral' | 'accent' | 'ib-brand-pink' | 'ib-brand-dark-blue' | 'ib-brand-orange' | 'ib-brand-pastel-yellow';
};
