// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type LinkCardList = {
  /**
   * Liste-type
   */
  list:
    | {
        /**
         * Selected
         */
        _selected: 'automatic';

        /**
         * Automatisk liste
         */
        automatic: {
          /**
           * Innholdstyper som skal hentes
           */
          contentTypes: Array<string> | string;

          /**
           * Hent kun barn av dette innholdet
           */
          parentContent?: string;

          /**
           * Vis tittel til innholdet som er valgt over
           */
          showHeading: boolean;

          /**
           * Maks antall innhold
           */
          limit?: number;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: 'manual';

        /**
         * Manuell liste
         */
        manual: {
          /**
           * Innhold i listen
           */
          contents: Array<string> | string;
        };
      };

  /**
   * Visning
   */
  displayType: 'withImage' | 'withIcon' | 'withIconBg' | 'none' | 'withImageAndIcon';

  /**
   * Antall lenkekort pr. rad
   */
  nEachRow: '0' | '2-3' | '2-4' | '1' | '2' | '3' | '4';

  /**
   * Skjul pil
   */
  hideArrow: boolean;

  /**
   * Skjul type-tag
   */
  hideTag: boolean;

  /**
   * Vis beskrivelse på kortene
   */
  showDescription: boolean;

  /**
   * Bakgrunn
   */
  color: 'white' | 'brand';
};
