apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: idebanken-frontend
  namespace: idebanken
  labels:
    team: idebanken
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: '50M'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
spec:
  ingresses:
  {{#each ingress as |url|}}
      - {{url}}
  {{/each}}
  image: '{{ image }}'
  port: 4242
  liveness:
    path: /api/isAlive
    initialDelay: 20
    timeout: 10
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /api/isReady
    initialDelay: 20
    timeout: 10
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  replicas:
    min: {{ replicas.min }}
    max: {{ replicas.max }}
    cpuThresholdPercentage: 60
  envFrom:
    - secret: idebanken-frontend
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  accessPolicy:
    outbound:
      rules:
        - application: idebanken-search-api
      external:
        - host: {{external-host}}
        - host: se.api.anpdm.com # APSIS PRO API
        - host: ingest.staging.skyra.no
        - host: survey.skyra.no
