apiVersion: aiven.io/v1alpha1
kind: OpenSearch
metadata:
  name: opensearch-idebanken-search
  namespace: idebanken
  labels:
    team: idebanken
spec:
  plan: {{opensearch-plan}}
  project: {{opensearch-project}}
  userConfig:
    opensearch_version: "2"