// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type AktueltTypeTag = import('./aktuelt-type-tag').AktueltTypeTag;
export type Artikkel = import('./artikkel').Artikkel;
export type CrashCourseSlide = import('./crash-course-slide').CrashCourseSlide;
export type CrashCourse = import('./crash-course').CrashCourse;
export type Guide = import('./guide').Guide;
export type SectionPage = import('./section-page').SectionPage;
export type SingletonAktuelt = import('./singleton-aktuelt').SingletonAktuelt;
export type SingletonTheme = import('./singleton-theme').SingletonTheme;
export type SingletonType = import('./singleton-type').SingletonType;
export type SpecialPage = import('./special-page').SpecialPage;
export type ThemeTag = import('./theme-tag').ThemeTag;
export type TypeTag = import('./type-tag').TypeTag;
export type Video = import('./video').Video;
export type Virkemiddel = import('./virkemiddel').Virkemiddel;

declare global {
  namespace XP {
    interface ContentTypes {
      'idebanken:aktuelt-type-tag': AktueltTypeTag;
      'idebanken:artikkel': Artikkel;
      'idebanken:crash-course-slide': CrashCourseSlide;
      'idebanken:crash-course': CrashCourse;
      'idebanken:guide': Guide;
      'idebanken:section-page': SectionPage;
      'idebanken:singleton-aktuelt': SingletonAktuelt;
      'idebanken:singleton-theme': SingletonTheme;
      'idebanken:singleton-type': SingletonType;
      'idebanken:special-page': SpecialPage;
      'idebanken:theme-tag': ThemeTag;
      'idebanken:type-tag': TypeTag;
      'idebanken:video': Video;
      'idebanken:virkemiddel': Virkemiddel;
    }
  }
}
