// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Guide = import("./guide").Guide;

declare global {
  namespace XP {
    interface ContentTypes {
      "idebanken:guide": Guide;
    }
  }
}
