// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Artikkel = import('./artikkel').Artikkel;
export type Category = import('./category').Category;
export type CrashCourseSlide = import('./crash-course-slide').CrashCourseSlide;
export type CrashCourse = import('./crash-course').CrashCourse;
export type Guide = import('./guide').Guide;
export type SectionPage = import('./section-page').SectionPage;
export type SpecialPage = import('./special-page').SpecialPage;
export type Video = import('./video').Video;
export type Virkemiddel = import('./virkemiddel').Virkemiddel;

declare global {
  namespace XP {
    interface ContentTypes {
      'idebanken:artikkel': Artikkel;
      'idebanken:category': Category;
      'idebanken:crash-course-slide': CrashCourseSlide;
      'idebanken:crash-course': CrashCourse;
      'idebanken:guide': Guide;
      'idebanken:section-page': SectionPage;
      'idebanken:special-page': SpecialPage;
      'idebanken:video': Video;
      'idebanken:virkemiddel': Virkemiddel;
    }
  }
}
