// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type _3Column = {
  /**
   * Bakgrunnsfarge
   */
  bgColor: "bg-white" | "bg-extra-light-pink" | "bg-light-pink" | "bg-pink" | "bg-dark-blue";

  /**
   * Mobilvisning - Rekkefølge
   */
  stackOrder: "left-center-right" | "center-left-right" | "right-center-left";
};
