// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_BrandColor = {
  /**
   * Brand farger
   */
  brand: 'neutral' | 'ib-brand-pink' | 'ib-brand-dark-blue';
};
