// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type HighlightedBox = {
  /**
   * Ikon
   */
  icon?: string;

  /**
   * Tittel
   */
  title: string;

  /**
   * Farge
   */
  brand: 'blue' | 'pink';

  /**
   * Innhold
   */
  body: string;

  /**
   * Interne lenker
   */
  links?: Array<string> | string;

  /**
   * Eksterne lenker
   */
  linksAbsolute?: Array<string> | string;
};
