// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type SingleColumn = {
  /**
   * Bakgrunnsfarge
   */
  bgColor: "bg-white" | "bg-extra-light-pink" | "bg-light-pink" | "bg-pink" | "bg-dark-blue";

  /**
   * Farge på boks
   */
  boxColor?: "bg-white" | "bg-extra-light-pink" | "bg-light-pink" | "bg-pink" | "bg-dark-blue";

  /**
   * Avstand over
   */
  paddingTop?: "0" | "6" | "10";

  /**
   * Avstand under
   */
  paddingBottom?: "0" | "6" | "10";

  /**
   * Juster innhold
   */
  alignment: "left" | "center" | "right";

  /**
   * Vis bakgrunnsbilde
   */
  backgroundImage: boolean;
};
