// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type LinkCard = {
  /**
   * Select link type
   */
  blockOptionSet:
    | {
        /**
         * Selected
         */
        _selected: 'internalLink';

        /**
         * Internal URL
         */
        internalLink: {
          /**
           * Select content
           */
          ideBankContentSelector?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: 'externalLink';

        /**
         * External URL
         */
        externalLink: {
          /**
           * Paste in URL
           */
          url?: string;
        };
      };

  /**
   * Lenketekst
   */
  text?: string;

  /**
   * Beskrivelse
   */
  description?: string;

  /**
   * Brand farger
   */
  brand: 'neutral' | 'ib-brand-pink' | 'ib-brand-dark-blue';

  /**
   * Bilde
   */
  image?: string;

  /**
   * Ikon
   */
  iconName?: 'hand-shake-heart' | 'reception' | 'chat-2' | 'hand-shake' | 'person-group' | 'task-list' | 'clock';

  /**
   * Ikonens bakgrunnsfarge
   */
  iconColor?: 'bg-white' | 'bg-pink' | 'bg-blue' | 'bg-orange' | 'bg-yellow' | 'bg-red';

  /**
   * Kategorier
   */
  categories?: Array<string> | string;

  /**
   * Tags
   */
  tags?: Array<'sykefravaer' | 'arbeidsmiljo' | 'partssamarbeid' | 'psykiskHelse' | 'inkludering' | 'omstilling'> | 'sykefravaer' | 'arbeidsmiljo' | 'partssamarbeid' | 'psykiskHelse' | 'inkludering' | 'omstilling';
};
