// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_LinkCard = {
  /**
   * Visning
   */
  displayType: 'none' | 'withIcon' | 'withImageAndIcon' | 'withImage';

  /**
   * Skjul pil
   */
  hideArrow: boolean;

  /**
   * Skjul type-tag
   */
  hideTag: boolean;

  /**
   * Vis beskrivelse
   */
  showDescription: boolean;

  /**
   * Bakgrunn
   */
  color: 'brand' | 'white';

  /**
   * Lenke-type
   */
  internalOrExternalLink:
    | {
        /**
         * Selected
         */
        _selected: 'internalLink';

        /**
         * Intern lenke
         */
        internalLink: {
          /**
           * Select content
           */
          contentId: string;

          /**
           * Overskriv lenketekst
           */
          linkText?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: 'externalLink';

        /**
         * Ekstern lenke
         */
        externalLink: {
          /**
           * URL
           */
          url: string;

          /**
           * Lenketekst
           */
          linkText: string;

          /**
           * Beskrivelse
           */
          description?: string;

          /**
           * Bilde
           */
          image?: string;

          /**
           * Ikon
           */
          icon?: string;
        };
      };
};
