// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_LinkCard = {
  /**
   * Brand farger
   */
  brand: 'neutral' | 'accent' | 'ib-brand-pink' | 'ib-brand-dark-blue' | 'ib-brand-orange' | 'ib-brand-pastel-yellow';

  /**
   * Visning
   */
  displayType: 'withIcon' | 'withImage';

  /**
   * Vis beskrivelse
   */
  showDescription: boolean;

  /**
   * Lenke-type
   */
  internalOrExternalLink:
    | {
        /**
         * Selected
         */
        _selected: 'internalLink';

        /**
         * Intern lenke
         */
        internalLink: {
          /**
           * Select content
           */
          contentId: string;

          /**
           * Overskriv lenketekst
           */
          linkText?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: 'externalLink';

        /**
         * Ekstern lenke
         */
        externalLink: {
          /**
           * URL
           */
          url: string;

          /**
           * Lenketekst
           */
          linkText: string;

          /**
           * Beskrivelse
           */
          description?: string;

          /**
           * Bilde
           */
          image?: string;

          /**
           * Ikon
           */
          icon?: string;

          /**
           * Ikonets bakgrunnsfarge
           */
          iconColor?: 'bg-white' | 'bg-pink' | 'bg-blue' | 'bg-orange' | 'bg-yellow' | 'bg-red';
        };
      };
};
