// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type SectionPage = {
  /**
   * Tittel
   */
  title: string;

  /**
   * Ingress
   */
  ingress: string;

  /**
   * Kort tittel (listevisning)
   */
  shortTitle?: string;

  /**
   * Kort beskrivelse (listevisning)
   */
  description?: string;

  /**
   * Overskriv bilde (listevisning)
   */
  image?: string;
};
