// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_CrashCoursePlan = {
  /**
   * Deler
   */
  parts?: Array<{
    /**
     * Etikett
     */
    label?: string;

    /**
     * Tittel
     */
    title?: string;

    /**
     * Underdeler
     */
    slides?: Array<{
      /**
       * Ikon
       */
      icon?: string;

      /**
       * Tekst
       */
      text?: string;
    }>;
  }>;
};
