// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_BoxColor = {
  /**
   * Farge på boks
   */
  boxColor?: 'neutral' | 'ib-brand-gray' | 'ib-brand-pink';
};
