// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Button = {
  /**
   * Select link button type
   */
  blockOptionSet:
    | {
        /**
         * Selected
         */
        _selected: "internalLink";

        /**
         * Internal URL
         */
        internalLink: {
          /**
           * Select content
           */
          ideBankContentSelector?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "externalLink";

        /**
         * External URL
         */
        externalLink: {
          /**
           * Paste in URL
           */
          url?: string;
        };
      };

  /**
   * Button text
   */
  text?: string;

  /**
   * Button variant
   */
  variant: "primary" | "secondary" | "tertiary";

  /**
   * Button size
   */
  size: "medium" | "small" | "xsmall";
};
