// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Button = {
  /**
   * Button text
   */
  text?: string;

  /**
   * Button variant
   */
  variant: "primary" | "secondary" | "tertiary";

  /**
   * Button size
   */
  size: "medium" | "small" | "xsmall";

  /**
   * My HtmlArea
   */
  myhtmlarea?: string;
};
