// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BrandColor = {
  /**
   * Brand farger
   */
  brand: 'neutral' | 'ib-brand-gray' | 'ib-brand-pink';
};
