// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Alignment = import('./alignment').XP_Alignment;
export type XP_BackgroundColor = import('./background-color').XP_BackgroundColor;
export type XP_BoxColor = import('./box-color').XP_BoxColor;
export type XP_CategorySelector = import('./category-selector').XP_CategorySelector;
export type XP_IconBackgroundColor = import('./icon-background-color').XP_IconBackgroundColor;
export type XP_IconName = import('./icon-name').XP_IconName;
export type XP_Image = import('./image').XP_Image;
export type XP_Link = import('./link').XP_Link;
export type XP_LinkGroups = import('./link-groups').XP_LinkGroups;
export type XP_LinkSelector = import('./link-selector').XP_LinkSelector;
export type XP_PaddingY = import('./padding-y').XP_PaddingY;
export type XP_SimpleTextEditor = import('./simple-text-editor').XP_SimpleTextEditor;
export type XP_Tags = import('./tags').XP_Tags;
export type XP_TitleIngress = import('./title-ingress').XP_TitleIngress;
