// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type TableOfContents = {
  /**
   * Tittel på innholdsfortegnelse
   */
  title?: string;

  /**
   * Sticky
   */
  sticky: boolean;
};
