// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type AktueltTags = import('./aktuelt-tags').AktueltTags;
export type Meta = import('./meta').Meta;
export type Tags = import('./tags').Tags;

declare global {
  interface XpXData {
    'idebanken'?: {
      'aktuelt-tags'?: AktueltTags;
      meta?: Meta;
      tags?: Tags;
    };
  }
}
