// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Meta = import('./meta').Meta;
export type Tags = import('./tags').Tags;

declare global {
  interface XpXData {
    'idebanken'?: {
      meta?: Meta;
      tags?: Tags;
    };
  }
}
