// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Category = import('./category').Category;
export type Meta = import('./meta').Meta;
export type ThirdParty = import('./third-party').ThirdParty;

declare global {
  interface XpXData {
    'idebanken'?: {
      category?: Category;
      meta?: Meta;
      'third-party'?: ThirdParty;
    };
  }
}
