// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_ThemeCardList = {
  /**
   * Antall artikler per last
   */
  pageSize: number;

  /**
   * Visning
   */
  displayType: 'withImage' | 'none';

  /**
   * Innhold øverst i listen
   */
  highlightedContent?: Array<string> | string;
};
