// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BoxColor = {
  /**
   * Farge på boks
   */
  boxColor?: 'bg-white' | 'bg-brand-white' | 'bg-extra-light-pink';
};
