// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type _2Column = import("./2-column")._2Column;
export type _3Column = import("./3-column")._3Column;
export type Panel2Column = import("./panel-2-column").Panel2Column;
export type SingleColumn = import("./single-column").SingleColumn;

declare global {
  interface XpLayoutMap {
    "idebanken:2-column": _2Column;
    "idebanken:3-column": _3Column;
    "idebanken:panel-2-column": Panel2Column;
    "idebanken:single-column": SingleColumn;
  }
}
