// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type IconName = {
  /**
   * Ikon
   */
  "icon-name"?: "hand-shake-heart" | "reception" | "chat-2" | "hand-shake" | "person-group" | "task-list" | "clock";
};
