// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_AktueltTypeTag = import('./aktuelt-type-tag').XP_AktueltTypeTag;
export type XP_Artikkel = import('./artikkel').XP_Artikkel;
export type XP_CrashCourseSlide = import('./crash-course-slide').XP_CrashCourseSlide;
export type XP_CrashCourse = import('./crash-course').XP_CrashCourse;
export type XP_Kjerneartikkel = import('./kjerneartikkel').XP_Kjerneartikkel;
export type XP_SectionPage = import('./section-page').XP_SectionPage;
export type XP_SingletonAktueltPage = import('./singleton-aktuelt-page').XP_SingletonAktueltPage;
export type XP_SingletonAktuelt = import('./singleton-aktuelt').XP_SingletonAktuelt;
export type XP_SingletonTheme = import('./singleton-theme').XP_SingletonTheme;
export type XP_SingletonType = import('./singleton-type').XP_SingletonType;
export type XP_SpecialPage = import('./special-page').XP_SpecialPage;
export type XP_ThemeTag = import('./theme-tag').XP_ThemeTag;
export type XP_TypeTag = import('./type-tag').XP_TypeTag;
export type XP_Video = import('./video').XP_Video;

declare global {
  namespace XP {
    interface ContentTypes {
      'idebanken:aktuelt-type-tag': XP_AktueltTypeTag;
      'idebanken:artikkel': XP_Artikkel;
      'idebanken:crash-course-slide': XP_CrashCourseSlide;
      'idebanken:crash-course': XP_CrashCourse;
      'idebanken:kjerneartikkel': XP_Kjerneartikkel;
      'idebanken:section-page': XP_SectionPage;
      'idebanken:singleton-aktuelt-page': XP_SingletonAktueltPage;
      'idebanken:singleton-aktuelt': XP_SingletonAktuelt;
      'idebanken:singleton-theme': XP_SingletonTheme;
      'idebanken:singleton-type': XP_SingletonType;
      'idebanken:special-page': XP_SpecialPage;
      'idebanken:theme-tag': XP_ThemeTag;
      'idebanken:type-tag': XP_TypeTag;
      'idebanken:video': XP_Video;
    }
  }
}
