// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Artikkel = import('./artikkel').XP_Artikkel;
export type XP_Category = import('./category').XP_Category;
export type XP_CrashCourseSlide = import('./crash-course-slide').XP_CrashCourseSlide;
export type XP_CrashCourse = import('./crash-course').XP_CrashCourse;
export type XP_Guide = import('./guide').XP_Guide;
export type XP_SectionPage = import('./section-page').XP_SectionPage;
export type XP_SpecialPage = import('./special-page').XP_SpecialPage;
export type XP_Virkemiddel = import('./virkemiddel').XP_Virkemiddel;

declare global {
  namespace XP {
    interface ContentTypes {
      'idebanken:artikkel': XP_Artikkel;
      'idebanken:category': XP_Category;
      'idebanken:crash-course-slide': XP_CrashCourseSlide;
      'idebanken:crash-course': XP_CrashCourse;
      'idebanken:guide': XP_Guide;
      'idebanken:section-page': XP_SectionPage;
      'idebanken:special-page': XP_SpecialPage;
      'idebanken:virkemiddel': XP_Virkemiddel;
    }
  }
}
