// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Category = import('./category').XP_Category;
export type XP_CrashCourseSlide = import('./crash-course-slide').XP_CrashCourseSlide;
export type XP_CrashCourse = import('./crash-course').XP_CrashCourse;
export type XP_Guide = import('./guide').XP_Guide;
export type XP_SectionPage = import('./section-page').XP_SectionPage;
export type XP_SpecialPage = import('./special-page').XP_SpecialPage;

declare global {
  namespace XP {
    interface ContentTypes {
      'idebanken:category': Category;
      'idebanken:crash-course-slide': CrashCourseSlide;
      'idebanken:crash-course': CrashCourse;
      'idebanken:guide': Guide;
      'idebanken:section-page': SectionPage;
      'idebanken:special-page': SpecialPage;
    }
  }
}
