// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Main = import("./main").Main;

declare global {
  interface XpPageMap {
    "idebanken:main": Main;
  }
}
