// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type FullWidth = import('./full-width').FullWidth;
export type Main = import('./main').Main;

declare global {
  interface XpPageMap {
    'idebanken:full-width': FullWidth;
    'idebanken:main': Main;
  }
}
