// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_NewsletterSignup = {
  /**
   * Tittel
   */
  title: string;

  /**
   * innhold
   */
  description?: string;

  /**
   * URL til Make-skjema (valgfritt)
   */
  formActionUrl?: string;
};
