// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type SectionGuidesView = {
  /**
   * Overstyr seksjon
   */
  overrideSection?: string;

  /**
   * Valgte veiledere (valgfritt)
   */
  selectedGuides?: Array<string> | string;

  /**
   * Maks antall veiledere
   */
  limit?: number;

  /**
   * Vis seksjonstittel
   */
  showHeading: boolean;

  /**
   * Korttype
   */
  cardType: 'withIcon' | 'withImage';
};
