// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type _2Column = import('./2-column')._2Column;
export type _3Column = import('./3-column')._3Column;
export type XP_SingleColumn = import('./single-column').XP_SingleColumn;

declare global {
  interface XpLayoutMap {
    'idebanken:2-column': _2Column;
    'idebanken:3-column': _3Column;
    'idebanken:single-column': SingleColumn;
  }
}
