// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_2Column = import('./2-column').XP_2Column;
export type XP_3Column = import('./3-column').XP_3Column;
export type XP_Card = import('./card').XP_Card;
export type XP_SingleColumn = import('./single-column').XP_SingleColumn;

declare global {
  interface XpLayoutMap {
    'idebanken:2-column': XP_2Column;
    'idebanken:3-column': XP_3Column;
    'idebanken:card': XP_Card;
    'idebanken:single-column': XP_SingleColumn;
  }
}
