// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Accordion = import("./accordion").Accordion;
export type Button = import("./button").Button;
export type Heading = import("./heading").Heading;
export type Image = import("./image").Image;
export type InfoBox = import("./info-box").InfoBox;
export type LinkCard = import("./link-card").LinkCard;
export type TextEditor = import("./text-editor").TextEditor;
export type TipPanel = import("./tip-panel").TipPanel;
export type TitleIngress = import("./title-ingress").TitleIngress;

declare global {
  interface XpPartMap {
    "idebanken:accordion": Accordion;
    "idebanken:button": Button;
    "idebanken:heading": Heading;
    "idebanken:image": Image;
    "idebanken:info-box": InfoBox;
    "idebanken:link-card": LinkCard;
    "idebanken:text-editor": TextEditor;
    "idebanken:tip-panel": TipPanel;
    "idebanken:title-ingress": TitleIngress;
  }
}
