// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Accordion = import("./accordion").Accordion;
export type Button = import("./button").Button;
export type DoubleInfoBox = import("./double-info-box").DoubleInfoBox;
export type Heading = import("./heading").Heading;
export type Image = import("./image").Image;
export type InfoBox = import("./info-box").InfoBox;
export type LinkPanel = import("./link-panel").LinkPanel;
export type TextEditor = import("./text-editor").TextEditor;
export type TipPanel = import("./tip-panel").TipPanel;

declare global {
  interface XpPartMap {
    "idebanken:accordion": Accordion;
    "idebanken:button": Button;
    "idebanken:double-info-box": DoubleInfoBox;
    "idebanken:heading": Heading;
    "idebanken:image": Image;
    "idebanken:info-box": InfoBox;
    "idebanken:link-panel": LinkPanel;
    "idebanken:text-editor": TextEditor;
    "idebanken:tip-panel": TipPanel;
  }
}
