// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Accordion = import('./accordion').Accordion;
export type Button = import('./button').Button;
export type Downloads = import('./downloads').Downloads;
export type ExpansionCard = import('./expansion-card').ExpansionCard;
export type Heading = import('./heading').Heading;
export type Image = import('./image').Image;
export type LinkCard = import('./link-card').LinkCard;
export type LinkCardList = import('./link-card-list').LinkCardList;
export type SearchView = import('./search-view').SearchView;
export type TableOfContents = import('./table-of-contents').TableOfContents;
export type TextEditor = import('./text-editor').TextEditor;
export type TitleIngress = import('./title-ingress').TitleIngress;

declare global {
  interface XpPartMap {
    'idebanken:accordion': Accordion;
    'idebanken:button': Button;
    'idebanken:downloads': Downloads;
    'idebanken:expansion-card': ExpansionCard;
    'idebanken:heading': Heading;
    'idebanken:image': Image;
    'idebanken:link-card': LinkCard;
    'idebanken:link-card-list': LinkCardList;
    'idebanken:search-view': SearchView;
    'idebanken:table-of-contents': TableOfContents;
    'idebanken:text-editor': TextEditor;
    'idebanken:title-ingress': TitleIngress;
  }
}
