// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type _3Column = {
  /**
   * Bakgrunnsfarge
   */
  bgColor: 'bg-white' | 'bg-extra-light-pink' | 'bg-light-pink' | 'bg-pink' | 'bg-dark-blue';

  /**
   * Farge på boks
   */
  boxColor?: 'bg-white' | 'bg-extra-light-pink' | 'bg-light-pink' | 'bg-pink' | 'bg-dark-blue';

  /**
   * Avstand over
   */
  paddingTop?: 'pt-0' | 'pt-6' | 'pt-10';

  /**
   * Avstand under
   */
  paddingBottom?: 'pb-0' | 'pb-6' | 'pb-10';

  /**
   * Mobilvisning - Rekkefølge
   */
  stackOrder: 'left-center-right' | 'center-left-right' | 'right-center-left';
};
