// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BackgroundColor = import("./background-color").BackgroundColor;
export type LinkSelector = import("./link-selector").LinkSelector;
export type SimpleTextEditor = import("./simple-text-editor").SimpleTextEditor;
export type TitleIngress = import("./title-ingress").TitleIngress;
