// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Alignment = import('./alignment').Alignment;
export type BackgroundColor = import('./background-color').BackgroundColor;
export type BoxColor = import('./box-color').BoxColor;
export type BrandColor = import('./brand-color').BrandColor;
export type Color = import('./color').Color;
export type DisplayImageOrIcon = import('./display-image-or-icon').DisplayImageOrIcon;
export type HeadingColor = import('./heading-color').HeadingColor;
export type Icon = import('./icon').Icon;
export type Image = import('./image').Image;
export type LinkGroups = import('./link-groups').LinkGroups;
export type LinkSelector = import('./link-selector').LinkSelector;
export type OverrideWidth = import('./override-width').OverrideWidth;
export type PaddingY = import('./padding-y').PaddingY;
export type SimpleTextEditor = import('./simple-text-editor').SimpleTextEditor;
export type TitleIngress = import('./title-ingress').TitleIngress;
