// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Alignment = import("./alignment").Alignment;
export type BackgroundColor = import("./background-color").BackgroundColor;
export type BoxColor = import("./box-color").BoxColor;
export type IconBackgroundColor = import("./icon-background-color").IconBackgroundColor;
export type IconName = import("./icon-name").IconName;
export type Image = import("./image").Image;
export type LinkGroups = import("./link-groups").LinkGroups;
export type LinkSelector = import("./link-selector").LinkSelector;
export type PaddingY = import("./padding-y").PaddingY;
export type SimpleTextEditor = import("./simple-text-editor").SimpleTextEditor;
export type Tags = import("./tags").Tags;
export type TitleIngress = import("./title-ingress").TitleIngress;
