// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Image = {
  /**
   * Velg et bilde
   */
  image: string;

  /**
   * Inkluder bildetekst
   */
  includeCaption: boolean;

  /**
   * Overskriv bildetekst
   */
  overrideCaption?: string;

  /**
   * Skjul på mobil
   */
  hideOnMobile: boolean;

  /**
   * Dekorativt bilde (skjul fra skjermleser)
   */
  decorative: boolean;

  /**
   * Bilde størrelse
   */
  'image-size':
    | {
        /**
         * Selected
         */
        _selected: 'aspect-ratio';

        /**
         * Størrelsesforhold
         */
        'aspect-ratio': {
          /**
           * Forhold
           */
          aspectRatio?: '16:9' | '4:3' | '1:1' | '3:4' | '9:16';

          /**
           * Maks bredde (px)
           */
          maxWidth?: number;

          /**
           * Avrundede kanter
           */
          roundedCorners: boolean;

          /**
           * Sentrer horisontalt
           */
          centerHorizontally: boolean;

          /**
           * Sentrer vertikalt
           */
          centerVertically: boolean;

          /**
           * X-Polstring rundt bildet (px)
           */
          paddingX?: number;

          /**
           * Y-Polstring rundt bildet (px)
           */
          paddingY?: number;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: 'standard-size';

        /**
         * Standard størrelse
         */
        'standard-size': {
          /**
           * Bredde
           */
          standardWidth: 'standard' | 'medium' | 'large';
        };
      }
    | {
        /**
         * Selected
         */
        _selected: 'custom-size';

        /**
         * Egendefinert størrelse og styling
         */
        'custom-size': {
          /**
           * Egendefinert bredde (px)
           */
          width?: number;

          /**
           * Egendefinert høyde (px)
           */
          height?: number;

          /**
           * Avrundet hjørne (px)
           */
          borderRadius?: number;

          /**
           * Sentrer horisontalt
           */
          centerHorizontally: boolean;

          /**
           * Sentrer vertikalt
           */
          centerVertically: boolean;

          /**
           * X-Polstring rundt bildet (px)
           */
          paddingX?: number;

          /**
           * Y-Polstring rundt bildet (px)
           */
          paddingY?: number;

          /**
           * Vis kantlinje
           */
          border: boolean;

          /**
           * Kantlinje avstand (px)
           */
          borderDistance?: number;

          /**
           * Rundinger
           */
          circles?: Array<{
            /**
             * Farge
             */
            color: 'pink' | 'red' | 'blue';

            /**
             * Størrelse (px)
             */
            size?: number;

            /**
             * Avstand fra bunn (y-akse i px)
             */
            bottom?: number;

            /**
             * Avstand fra venstre (x-akse i px)
             */
            left?: number;
          }>;

          /**
           * Komprimer bilde (1-100/mest-minst. 0=ingen)
           */
          scale?: number;
        };
      };
};
