// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_ExpansionCard = {
  /**
   * Tittel
   */
  header?: string;

  /**
   * Beskrivelse
   */
  description?: string;

  /**
   * Innhold
   */
  simpleTextEditor?: string;

  /**
   * Brand farger
   */
  brand: 'neutral' | 'accent' | 'ib-brand-pink' | 'ib-brand-dark-blue' | 'ib-brand-orange' | 'ib-brand-pastel-yellow';
};
