// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_ThemeTag = {
  /**
   * Tittel
   */
  title: string;

  /**
   * Ingress
   */
  ingress: string;

  /**
   * Kort tittel (listevisning)
   */
  shortTitle?: string;

  /**
   * Kort beskrivelse (listevisning)
   */
  description?: string;

  /**
   * Overskriv lenkekort bilde
   */
  overrideImage?: string;

  /**
   * Ikon
   */
  icon?: string;
};
