// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_IconBackgroundColor = {
  /**
   * Ikonets bakgrunnsfarge
   */
  iconColor?: 'bg-white' | 'ib-pink-400A' | 'bg-blue' | 'bg-orange' | 'bg-yellow' | 'bg-red';
};
