// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_IconBackgroundColor = {
    /**
     * Ikonets bakgrunnsfarge
     */
    iconColor?: 'ib-brand-white' | 'ib-pink-400A' | 'ib-dark-blue-400A' | 'ib-orange-400A'
}
