// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Heading = {
  /**
   * Heading text
   */
  text?: string;

  /**
   * Heading level
   */
  level: '1' | '2' | '3' | '4' | '5' | '6';

  /**
   * Heading size
   */
  size: 'xlarge' | 'large' | 'medium' | 'small' | 'xsmall';
};
