// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type TitleIngress = {
  /**
   * Tittel bilde
   */
  image?: string;

  /**
   * Bakgrunnsfarge
   */
  bgColor: 'bg-white' | 'bg-extra-light-pink' | 'bg-light-pink' | 'bg-pink' | 'bg-dark-blue';
};
