// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Alignment = {
  /**
   * Juster innhold x-akse
   */
  xAlignment?: 'center' | 'right';

  /**
   * Juster innhold y-akse
   */
  yAlignment?: 'center' | 'bottom';
};
