// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Image = {
  /**
   * Velg et bilde
   */
  image: string;

  /**
   * Skjul på mobil
   */
  hideOnMobile: boolean;

  /**
   * Dekorativt bilde (skjul fra skjermleser)
   */
  decorative: boolean;

  /**
   * Bredde (px)
   */
  width?: number;

  /**
   * Høyde (px)
   */
  height?: number;

  /**
   * Avrundet hjørne (px)
   */
  borderRadius?: number;

  /**
   * Sentrer horisontalt
   */
  centerHorizontally: boolean;

  /**
   * Sentrer vertikalt
   */
  centerVertically: boolean;

  /**
   * X-Polstring rundt bildet (px)
   */
  paddingX?: number;

  /**
   * Y-Polstring rundt bildet (px)
   */
  paddingY?: number;

  /**
   * Vis kantlinje
   */
  border: boolean;

  /**
   * Kantlinje avstand (px)
   */
  borderDistance?: number;

  /**
   * Rundinger
   */
  circles?: Array<{
    /**
     * Farge
     */
    color: 'pink' | 'red' | 'blue';

    /**
     * Størrelse (px)
     */
    size?: number;

    /**
     * Avstand fra bunn (y-akse i px)
     */
    bottom?: number;

    /**
     * Avstand fra venstre (x-akse i px)
     */
    left?: number;
  }>;

  /**
   * Komprimer bilde (1-100/mest-minst. 0=ingen)
   */
  scale?: number;
};
