// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Tags = {
  /**
   * Tags
   */
  tags?: Array<'sykefravaer' | 'arbeidsmiljo' | 'partssamarbeid' | 'psykiskHelse' | 'inkludering' | 'omstilling'> | 'sykefravaer' | 'arbeidsmiljo' | 'partssamarbeid' | 'psykiskHelse' | 'inkludering' | 'omstilling';
};
