// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_FullWidth = import('./full-width').XP_FullWidth;
export type XP_Main = import('./main').XP_Main;

declare global {
  interface XpPageMap {
    'idebanken:full-width': XP_FullWidth;
    'idebanken:main': XP_Main;
  }
}
