// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Meta = {
  /**
   * Ikon
   */
  icon?: string;

  /**
   * Ikonets bakgrunnsfarge
   */
  iconColor?: 'ib-brand-white' | 'ib-pink-400A' | 'ib-dark-blue-400A' | 'ib-orange-400A' | 'ib-pastel-yellow-300A';

  /**
   * Skjul fra listevisning
   */
  hideFromListViews: boolean;

  /**
   * Skjul fra internsøk
   */
  hideFromInternalSearch: boolean;
};
