// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Meta = {
  /**
   * Skjul fra listevisning
   */
  hideFromListViews: boolean;

  /**
   * Skjul fra internsøk
   */
  hideFromInternalSearch: boolean;
};
