// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type AktueltTypeTag = {
  /**
   * Farge
   */
  color?: 'ax-danger-400' | 'ax-meta-purple-600' | 'ax-success-800' | 'ax-accent-600' | 'ax-warning-400' | 'ax-warning-500';
};
