// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type _2Column = {
  /**
   * Bakgrunnsfarge
   */
  bgColor: "bg-white" | "bg-extra-light-pink" | "bg-light-pink" | "bg-pink" | "bg-dark-blue";

  /**
   * Farge på boks
   */
  boxColor?: "bg-white" | "bg-extra-light-pink" | "bg-light-pink" | "bg-pink" | "bg-dark-blue";

  /**
   * Avstand over
   */
  paddingTop?: "0" | "6" | "10";

  /**
   * Avstand under
   */
  paddingBottom?: "0" | "6" | "10";

  /**
   * Venstre Kolonne - Bredde
   */
  leftSpan: "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "11";

  /**
   * Venstre kolonne øverst for mobilvisning
   */
  breakLeftFirst: boolean;
};
