// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type _2Column = {
  /**
   * Bakgrunnsfarge
   */
  bgColor: 'neutral' | 'ib-brand-gray' | 'ib-brand-pink';

  /**
   * Farge på boks
   */
  boxColor?: 'neutral' | 'ib-brand-gray' | 'ib-brand-pink';

  /**
   * Avstand over
   */
  paddingTop?: 'pt-0' | 'pt-6' | 'pt-10';

  /**
   * Avstand under
   */
  paddingBottom?: 'pb-0' | 'pb-6' | 'pb-10';

  /**
   * Overstyr bredde
   */
  overrideWidth?: 'text' | 'md' | 'lg' | 'xl' | '2xl';

  /**
   * Fjern gutters (ekstra padding)
   */
  noGutters: boolean;

  /**
   * Venstre Kolonne - Bredde
   */
  leftSpan: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11';

  /**
   * Venstre kolonne øverst for mobilvisning
   */
  breakLeftFirst: boolean;

  /**
   * Juster innhold x-akse
   */
  xAlignment?: 'center' | 'right';

  /**
   * Juster innhold y-akse
   */
  yAlignment?: 'center' | 'bottom';

  /**
   * Vis separator mellom kolonner
   */
  separator: boolean;
};
