// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Heading = {
  /**
   * Heading text
   */
  text?: string;

  /**
   * Heading level
   */
  level: '1' | '2' | '3' | '4' | '5' | '6';

  /**
   * Heading size
   */
  size: 'display' | '3xlarge' | '2xlarge' | 'xlarge' | 'large' | 'medium' | 'small' | 'xsmall';

  /**
   * Ingress
   */
  headingLede?: string;

  /**
   * Vis ingress på 1/2 sjermbredde
   */
  halfWidth: boolean;
};
