// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type NewsletterSignup = {
  /**
   * Tittel
   */
  title: string;

  /**
   * Innhold
   */
  description?: string;

  /**
   * Make-lenke
   */
  makeFormUrl?: string;
};
