// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_OverrideWidth = {
  /**
   * Overstyr bredde
   */
  overrideWidth?: 'text' | 'md' | 'lg' | 'xl' | '2xl';

  /**
   * Fjern gutters (ekstra padding)
   */
  noGutters: boolean;
};
