// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Button = {
  /**
   * Lenke-type
   */
  internalOrExternalLink:
    | {
        /**
         * Selected
         */
        _selected: 'internalLink';

        /**
         * Intern lenke
         */
        internalLink: {
          /**
           * Innhold som skal lenkes til
           */
          contentId: string;

          /**
           * Overskriv lenketekst
           */
          linkText?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: 'externalLink';

        /**
         * Ekstern lenke
         */
        externalLink: {
          /**
           * URL (https://...)
           */
          url: string;

          /**
           * Lenketekst
           */
          linkText?: string;
        };
      };

  /**
   * Button variant
   */
  variant: 'primary' | 'secondary' | 'tertiary' | 'link';

  /**
   * Button size
   */
  size: 'medium' | 'small' | 'xsmall';
};
