// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Artikkel = {
  /**
   * Hoved artikkelbilde
   */
  heroImage?: string;

  /**
   * Overskriv artikkelbildetekst
   */
  overrideHeroImageText?: string;

  /**
   * Tittel
   */
  title: string;

  /**
   * Ingress
   */
  ingress: string;

  /**
   * Kort tittel (listevisning)
   */
  shortTitle?: string;

  /**
   * Kort beskrivelse (listevisning)
   */
  description?: string;

  /**
   * Overskriv lenkekort bilde
   */
  overrideImage?: string;

  /**
   * Forfatter(e)
   */
  authors: Array<string> | string;
};
