// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Card = {
  /**
   * Heading prefix (f. eks 1, A eller I)
   */
  prefix?: string;

  /**
   * Heading text
   */
  heading?: string;

  /**
   * Fremhevet (skygge)
   */
  shadow: boolean;

  /**
   * Bakgrunnsfarge
   */
  bgColor: 'bg-white' | 'bg-brand-white' | 'bg-extra-light-pink' | 'bg-light-pink' | 'bg-pink' | 'bg-dark-blue';

  /**
   * Heading farge
   */
  headingColor?: 'bg-white' | 'bg-extra-light-pink' | 'bg-light-pink' | 'bg-pink' | 'bg-dark-blue';

  /**
   * Avstand over
   */
  paddingTop?: 'pt-0' | 'pt-6' | 'pt-10';

  /**
   * Avstand under
   */
  paddingBottom?: 'pb-0' | 'pb-6' | 'pb-10';

  /**
   * Overstyr bredde
   */
  overrideWidth?: 'text' | 'md' | 'lg' | 'xl' | '2xl';

  /**
   * Juster innhold x-akse
   */
  xAlignment?: 'center' | 'right';

  /**
   * Juster innhold y-akse
   */
  yAlignment?: 'center' | 'bottom';

  /**
   * Vis på 1/2 sjermbredde og sentrert
   */
  centerHalfWidth: boolean;

  /**
   * Juster innhold x-akse
   */
  xAlignment?: 'center' | 'right';

  /**
   * Juster innhold y-akse
   */
  yAlignment?: 'center' | 'bottom';
};
