// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_HighlightedBox = {
  /**
   * Ikon
   */
  icon?: string;

  /**
   * Tittel
   */
  title: string;

  /**
   * Brand farger
   */
  brand: 'neutral' | 'accent' | 'ib-brand-pink' | 'ib-brand-dark-blue' | 'ib-brand-orange' | 'ib-brand-pastel-yellow';

  /**
   * Innhold
   */
  body: string;

  /**
   * Interne lenker
   */
  links?: Array<string> | string;

  /**
   * Eksterne lenker
   */
  linksAbsolute?: Array<string> | string;
};
