// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type LinkGroups = {
  /**
   * Lenkegrupper
   */
  linkGroups?: Array<{
    /**
     * Tittel
     */
    title?: string;

    /**
     * Lenker
     */
    links?: Array<{
      /**
       * Lenke
       */
      link: string;

      /**
       * Overskriv lenketekst
       */
      linkText?: string;
    }>;
  }>;
};
