// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type LinkGroups = {
  /**
   * Lenkegrupper
   */
  linkGroups?: Array<{
    /**
     * Tittel
     */
    title?: string;

    /**
     * Lenker
     */
    links?: Array<{
      /**
       * Lenke-type
       */
      internalOrExternalLink:
        | {
            /**
             * Selected
             */
            _selected: 'internalLink';

            /**
             * Intern lenke
             */
            internalLink: {
              /**
               * Innhold som skal lenkes til
               */
              contentId: string;

              /**
               * Overskriv lenketekst
               */
              linkText?: string;
            };
          }
        | {
            /**
             * Selected
             */
            _selected: 'externalLink';

            /**
             * Ekstern lenke
             */
            externalLink: {
              /**
               * URL (https://...)
               */
              url: string;

              /**
               * Lenketekst
               */
              linkText?: string;
            };
          };
    }>;
  }>;
};
