// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Meta = {
  /**
   * Skjul fra listevisning
   */
  hideFromListViews: boolean;

  /**
   * Skjul fra internsøk
   */
  hideFromInternalSearch: boolean;

  /**
   * Søkbare nøkkelord
   */
  keywords?: Array<string> | string;
};
