// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Meta = {
  /**
   * Bilde
   */
  image?: string;

  /**
   * Ikon
   */
  icon?: string;

  /**
   * Ikonens bakgrunnsfarge
   */
  iconColor?: 'bg-white' | 'bg-pink' | 'bg-blue' | 'bg-orange' | 'bg-yellow' | 'bg-red';
};
