// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type XP_Meta = {
  /**
   * Bilde
   */
  image?: string;

  /**
   * Ikon
   */
  iconName?: 'hand-shake-heart' | 'reception' | 'chat-2' | 'hand-shake' | 'person-group' | 'task-list' | 'clock' | 'link' | 'light-bulb';

  /**
   * Ikonens bakgrunnsfarge
   */
  iconColor?: 'bg-white' | 'bg-pink' | 'bg-blue' | 'bg-orange' | 'bg-yellow' | 'bg-red';
};
