name: Test Gradle application
on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'gradle'
          cache-dependency-path: ${{ inputs.working-directory }}/gradle.properties
      - name: Test Gradle application
        run: ./gradlew test