name: Test Gradle application
on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json
      - name: Install node.js dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Run unit tests
        run: npm run test
