name: JVM app build and deploy
run-name: JVM app build and deploy - ${{ inputs.app_directory }} to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: test
        options:
          - test
          - prod
      app_directory:
        type: choice
        description: App to deploy. Used by build to postfix the artifact name
        required: true
        options:
          - apps/idebanken-search-api
        default: "apps/idebanken-search-api"

jobs:
  deploy:
    name: Build image and deploy to nais
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: read
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.app_directory }}
    env:
      CLUSTER: ${{ inputs.environment == 'prod' && 'prod-gcp' || 'dev-gcp' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build application
        run: |
          ./gradlew clean build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: idebanken
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: .nais/${{ inputs.app_directory }}.yml
          VAR: image=${{steps.docker-build-push.outputs.image}}
          VARS: .nais/${{ env.CLUSTER }}/${{ inputs.app_directory }}.yml
