name: Deploy Opensearch
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to deploy to
        required: true
        default: test
        options:
          - test
          - prod

jobs:
  deploy-opensearch:
    name: Deploy Opensearch instance to cluster
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      CLUSTER: ${{ inputs.environment == 'prod' && 'prod-gcp' || 'dev-gcp' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: .nais/opensearch.yml
          VARS: .nais/${{ env.CLUSTER }}/opensearch.yml