name: Deploy Opensearch
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: dev-gcp
        options:
          - dev-gcp
          - prod-gcp

jobs:
  deploy-opensearch:
    name: Deploy Opensearch instance to cluster
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    env:
      CLUSTER: ${{ inputs.environment == 'prod' && 'prod-gcp' || 'dev-gcp' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: ./nais/opensearch.yml
          VARS: ./nais/${{ env.CLUSTER }}/opensearch.yml