// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Accordion = {
  /**
   * Accordion
   */
  accordionItems: Array<{
    /**
     * Accordion header
     */
    header?: string;

    /**
     * Innhold
     */
    simpleTextEditor?: string;
  }>;
};
