// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Accordion = {
  /**
   * Bakgrunnsfarge
   */
  bgColor: "bg-white" | "bg-extra-light-pink" | "bg-light-pink" | "bg-pink" | "bg-dark-blue";

  /**
   * Accordion
   */
  accordionItem: Array<{
    /**
     * Accordion header
     */
    header?: string;

    /**
     * Innhold
     */
    simpleTextEditor?: string;
  }>;
};
