// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Accordion = {
  /**
   * Brand farger
   */
  brand: 'neutral' | 'accent' | 'ib-brand-pink' | 'ib-brand-dark-blue' | 'ib-brand-orange' | 'ib-brand-pastel-yellow';

  /**
   * Accordion
   */
  accordionItems: Array<{
    /**
     * Accordion header
     */
    header?: string;

    /**
     * Innhold
     */
    simpleTextEditor?: string;
  }>;
};
